github.api.url=https://api.github.com/repos/Flowseal/zapret-discord-youtube/releases/latest
app.dir.name=zapret
console.encoding=CP866
app.logs.max_lines=300

zapret.process.name=zapret.exe
zapret.install.dir=zapret
zapret.service.bat=service.bat